# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import actuators_pb2 as actuators__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in actuators_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActuatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.controlLightBulb = channel.unary_unary(
                '/actuators.ActuatorService/controlLightBulb',
                request_serializer=actuators__pb2.RequestLightBulb.SerializeToString,
                response_deserializer=actuators__pb2.Response.FromString,
                _registered_method=True)
        self.controlAC = channel.unary_unary(
                '/actuators.ActuatorService/controlAC',
                request_serializer=actuators__pb2.RequestAC.SerializeToString,
                response_deserializer=actuators__pb2.Response.FromString,
                _registered_method=True)
        self.controlSprinkler = channel.unary_unary(
                '/actuators.ActuatorService/controlSprinkler',
                request_serializer=actuators__pb2.RequestSprinkler.SerializeToString,
                response_deserializer=actuators__pb2.Response.FromString,
                _registered_method=True)


class ActuatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def controlLightBulb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def controlAC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def controlSprinkler(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActuatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'controlLightBulb': grpc.unary_unary_rpc_method_handler(
                    servicer.controlLightBulb,
                    request_deserializer=actuators__pb2.RequestLightBulb.FromString,
                    response_serializer=actuators__pb2.Response.SerializeToString,
            ),
            'controlAC': grpc.unary_unary_rpc_method_handler(
                    servicer.controlAC,
                    request_deserializer=actuators__pb2.RequestAC.FromString,
                    response_serializer=actuators__pb2.Response.SerializeToString,
            ),
            'controlSprinkler': grpc.unary_unary_rpc_method_handler(
                    servicer.controlSprinkler,
                    request_deserializer=actuators__pb2.RequestSprinkler.FromString,
                    response_serializer=actuators__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'actuators.ActuatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('actuators.ActuatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActuatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def controlLightBulb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actuators.ActuatorService/controlLightBulb',
            actuators__pb2.RequestLightBulb.SerializeToString,
            actuators__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def controlAC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actuators.ActuatorService/controlAC',
            actuators__pb2.RequestAC.SerializeToString,
            actuators__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def controlSprinkler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/actuators.ActuatorService/controlSprinkler',
            actuators__pb2.RequestSprinkler.SerializeToString,
            actuators__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
