# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actuators.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'actuators.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61\x63tuators.proto\x12\tactuators\"<\n\x10RequestLightBulb\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\"J\n\tRequestAC\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x0e\n\x06\x61\x63tive\x18\x04 \x01(\x08\"<\n\x10RequestSprinkler\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\"2\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\xd5\x01\n\x0f\x41\x63tuatorService\x12\x44\n\x10\x63ontrolLightBulb\x12\x1b.actuators.RequestLightBulb\x1a\x13.actuators.Response\x12\x36\n\tcontrolAC\x12\x14.actuators.RequestAC\x1a\x13.actuators.Response\x12\x44\n\x10\x63ontrolSprinkler\x12\x1b.actuators.RequestSprinkler\x1a\x13.actuators.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actuators_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTLIGHTBULB']._serialized_start=30
  _globals['_REQUESTLIGHTBULB']._serialized_end=90
  _globals['_REQUESTAC']._serialized_start=92
  _globals['_REQUESTAC']._serialized_end=166
  _globals['_REQUESTSPRINKLER']._serialized_start=168
  _globals['_REQUESTSPRINKLER']._serialized_end=228
  _globals['_RESPONSE']._serialized_start=230
  _globals['_RESPONSE']._serialized_end=280
  _globals['_ACTUATORSERVICE']._serialized_start=283
  _globals['_ACTUATORSERVICE']._serialized_end=496
# @@protoc_insertion_point(module_scope)
